/**
 * Helpers for the Hugging Face copy of the dataset.
 *
 * The export dialog offers a Python snippet that pulls the same subset of
 * papers the user has filtered to on the site. Translating the interface
 * filters into pandas is fiddly in two ways worth knowing about:
 *
 *  - The parquet on Hugging Face stores `AuthorNames-Deduped`, `Award` and
 *    `Resources` as list columns, while the CSV the site loads stores them as
 *    semicolon separated strings. Generated code has to use list semantics.
 *  - The interface filters on *display* values, which differ from what is
 *    stored: the venue `Vis` shows as `VIS`, awards show as full names rather
 *    than codes, and author names have their dblp ordinal stripped.
 *
 * The maps below invert `getConference`, `getAward` and `getResourceName` in
 * `src/stores/paperDataStore.ts`; if those change, these must change too.
 */

export const HF_REPO_ID = 'DevLan/vispubs';
export const HF_DATASET_URL = `https://huggingface.co/datasets/${HF_REPO_ID}`;

const VERSION_FILE_URL = '/data/hf_version.json';

export interface HfVersionInfo {
  version: string;
  published?: string;
}

/**
 * Read the release recorded by the last publish, or null when unavailable.
 *
 * The file only exists once a release has been published, so every caller has
 * to cope with it being missing rather than treating that as an error.
 */
export async function fetchHfVersion(): Promise<HfVersionInfo | null> {
  try {
    const response = await fetch(window.location.origin + VERSION_FILE_URL);
    if (!response.ok) return null;
    const data = await response.json();
    if (typeof data?.version !== 'string') return null;
    return { version: data.version, published: data.published };
  } catch {
    return null;
  }
}

const VENUE_TO_STORED: Record<string, string> = { VIS: 'Vis' };

const AWARD_TO_CODE: Record<string, string> = {
  'Best Paper': 'BP',
  'Honorable Mention': 'HM',
  'Test of Time': 'TT',
  'Best Application': 'BA',
  'Best Case Study': 'BCS',
};

const RESOURCE_TO_CODE: Record<string, string> = {
  Paper: 'P',
  Video: 'V',
  Code: 'C',
  Data: 'D',
  Website: 'PW',
  Other: 'O',
};

/** The resource filter carries this alongside real resources, but it maps to
 * the `Accessible` boolean column rather than the `Resources` list. */
const ACCESSIBLE_LABEL = 'Accessible';

export interface HfSnippetFilters {
  /** Pin to this release, or null for whatever is current. */
  revision: string | null;
  venues: string[];
  /** Only set when the range is narrower than the full extent. */
  yearRange: { min: number; max: number } | null;
  awards: string[];
  /** Display labels, possibly including 'Accessible'. */
  resources: string[];
  collection: { title: string; dois: string[] } | null;
  searchText: string;
  matchCase: boolean;
  useRegex: boolean;
}

/** Render a JS string as a Python string literal. JSON escaping is a subset of
 * Python's, so this is safe for quotes, backslashes and control characters. */
function py(value: string): string {
  return JSON.stringify(value);
}

function pyList(values: string[], indent = '    '): string {
  if (values.length <= 3) {
    return `[${values.map(py).join(', ')}]`;
  }
  const body = values.map((v) => `${indent}${py(v)},`).join('\n');
  return `[\n${body}\n]`;
}

function pySet(values: string[]): string {
  return `{${values.map(py).join(', ')}}`;
}

/**
 * Build a Python snippet reproducing the supplied filters.
 *
 * Only filters that are actually active are emitted, so an unfiltered list
 * yields a short snippet that just loads the dataset.
 */
export function buildHfSnippet(filters: HfSnippetFilters): string {
  const blocks: string[] = [];
  const needsRe = filters.searchText !== '';

  const imports = ['from datasets import load_dataset'];
  if (needsRe) imports.unshift('import re', '');

  const load =
    filters.revision === null
      ? `load_dataset(${py(HF_REPO_ID)})`
      : `load_dataset(${py(HF_REPO_ID)}, revision=${py(filters.revision)})`;

  blocks.push(
    [
      '# Generated by vispubs.com — reproduces the filters applied on the site.',
      '# pip install datasets pandas',
      '',
      ...imports,
      '',
      `ds = ${load}`,
      'df = ds["train"].to_pandas()',
    ].join('\n')
  );

  if (filters.venues.length > 0) {
    const stored = filters.venues.map((v) => VENUE_TO_STORED[v] ?? v);
    blocks.push(
      [
        '# Venue filter',
        `df = df[df["Conference"].isin(${pyList(stored)})]`,
      ].join('\n')
    );
  }

  if (filters.yearRange !== null) {
    const { min, max } = filters.yearRange;
    blocks.push(
      ['# Year filter', `df = df[df["Year"].between(${min}, ${max})]`].join(
        '\n'
      )
    );
  }

  if (filters.awards.length > 0) {
    const codes = filters.awards.map((a) => AWARD_TO_CODE[a] ?? a);
    blocks.push(
      [
        '# Award filter — Award is a list column, so match any of these codes',
        `awards = ${pySet(codes)}`,
        'df = df[df["Award"].apply(lambda xs: bool(awards.intersection(xs)))]',
      ].join('\n')
    );
  }

  const accessible = filters.resources.includes(ACCESSIBLE_LABEL);
  const resourceCodes = filters.resources
    .filter((r) => r !== ACCESSIBLE_LABEL)
    .map((r) => RESOURCE_TO_CODE[r] ?? r);

  if (resourceCodes.length > 0 || accessible) {
    const lines = ['# Resource filter'];
    if (resourceCodes.length > 0) {
      lines.push(
        `resources = ${pySet(resourceCodes)}`,
        'matches = df["Resources"].apply(lambda xs: bool(resources.intersection(xs)))'
      );
    } else {
      lines.push('matches = False');
    }
    if (accessible) {
      lines.push('# "Accessible" is its own column rather than a resource');
      lines.push('matches = matches | df["Accessible"]');
    }
    lines.push('df = df[matches]');
    blocks.push(lines.join('\n'));
  }

  if (filters.collection !== null) {
    blocks.push(
      [
        `# Collection: ${filters.collection.title}`,
        `collection = ${pyList(filters.collection.dois)}`,
        'df = df[df["DOI"].isin(collection)]',
      ].join('\n')
    );
  }

  if (filters.searchText !== '') {
    const mode = filters.useRegex ? 'regex' : 'plain text';
    const sensitivity = filters.matchCase
      ? 'case sensitive'
      : 'case insensitive';
    const containsArgs = [
      py(filters.searchText),
      `case=${filters.matchCase ? 'True' : 'False'}`,
      `regex=${filters.useRegex ? 'True' : 'False'}`,
    ];
    // The site's regexes carry the multiline flag; without it an anchored
    // pattern would behave differently against abstracts containing newlines.
    if (filters.useRegex) containsArgs.push('flags=re.M');

    blocks.push(
      [
        `# Search filter — ${mode}, ${sensitivity}`,
        '# The site matches authors, title and abstract joined by "¶", so a',
        '# regex can span those fields.',
        'def display_name(name):',
        '    # "Bei Wang 0001" is shown and searched as "Bei Wang".',
        '    parts = [c for c in name.split(" ") if not re.match(r"[+-]?\\d", c)]',
        '    return " ".join(parts)',
        '',
        'searchable = (',
        '    df["AuthorNames-Deduped"].apply(',
        '        lambda xs: "¶".join(display_name(a) for a in xs)',
        '    )',
        '    + "¶"',
        '    + df["Title"].fillna("")',
        '    + "¶"',
        '    + df["Abstract"].fillna("")',
        ')',
        `df = df[searchable.str.contains(${containsArgs.join(', ')})]`,
      ].join('\n')
    );
  }

  blocks.push(['print(f"{len(df)} papers")', 'print(df.head())'].join('\n'));

  return blocks.join('\n\n') + '\n';
}
